### PR TITLE
Fix for issue 20

### PR DESCRIPTION
**Pull request by sbugryn**
It seems only the "AT&T" arena has special characters, no other variables have this or any similar issues.
My fix is is to replace ${arena} with ${arena.replace(/&/g,"&")} in the 3 files it is used.

### CODE REVIEW

**Comment by xxhomey19** [comment]
Hi @sbugryn 
What do else files in /.idea go for? Are they necessary?

**Comment by sbugryn** [comment]
Sorry for late response, Github emails were going to the wrong folder in my email.
I am not sure why .idea files appear different, I did not change anything there.

**Comment by pedromql** [comment]
@sbugryn the .idea folder is part of the config files of your IDE.

`.idea/` should probably be added to the .gitignore file.
Or you could disable git from tracking that folder locally with something like `git rm -r --cached .idea`

**Comment by xxhomey19** [comment]
You can ignore those files and commit on this PR.

**Comment by xxhomey19** [comment]
Closed due to no update.

**Pull request closed without merging**
