### PR TITLE
Fix source map argument and add pck to package.json

### PR DESCRIPTION
**Pull request by jhamet93**
Added pkg to package.json to avoid the assumption its installed globally. Also fixed source map argument which was not working when specified as last argument.

### CODE REVIEW

**Comment by xxhomey19** [comment]
Source map works for me 😮

**Comment by jhamet93** [comment]
odd , I thought it was weird but my debugger wasn't getting hit until I moved its placement

**Comment by xxhomey19** [comment]
@jhamet93 

Could this PR only add pkg to package.json?

**Comment by jhamet93** [comment]
@xxhomey19 

yep just changed it only to add the module to package.json

**Pull request merged**
